name       : haskell-path-io
version    : 1.2.2
release    : 1
source     :
    - http://hackage.haskell.org/package/path-io-1.2.2/path-io-1.2.2.tar.gz : 72255f9d014285c87dd4c537f445a5448b2b64e81c4ee4759464b4b0e401fe46
license    : BSD-3-Clause
component  : programming.haskell
summary    : Interface to directory package for users of path. 
description: |
    Interface to directory package for users of path. 
builddeps  :
    - haskell-cabal-install
    - haskell-path
    - haskell-temporary
    - haskell-unix-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
