name       : haskell-path-io
version    : 1.4.2
release    : 3
source     :
    - https://hackage.haskell.org/package/path-io-1.4.2/path-io-1.4.2.tar.gz : 23c7f203347bc20e5649476e9b5df662a09ffbb8c1a2f3e658935845621d1d4b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Interface to directory package for users of path.
description: Interface to directory package for users of path.
builddeps  :
    - haskell-aeson-devel
    - haskell-cabal-install
    - haskell-path-devel
    - haskell-temporary-devel
    - haskell-unix-compat-devel
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-path-devel
        - haskell-temporary-devel
        - haskell-unix-compat-devel
networking : yes
setup      : |
    sed -i "s|4.12|4.10|g" path-io.cabal
    # sed -i "s|1.3|1.4|g" path-io.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
