name       : haskell-path-io
version    : 1.3.3
release    : 2
source     :
    - https://hackage.haskell.org/package/path-io-1.3.3/path-io-1.3.3.tar.gz : 2aec05914a7569f221cf73e25070fea5fad8125a9a93845e8d614a1c291e35bd
license    : BSD-3-Clause
component  : programming.haskell
summary    : Interface to directory package for users of path.
description: "Interface to directory package for users of path. \n"
builddeps  :
    - haskell-cabal-install
    - haskell-path
    - haskell-temporary
    - haskell-unix-compat
setup      : |
    sed -i "s|0.9|0.11|g" path-io.cabal
    sed -i "s|1.3|1.4|g" path-io.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
